name: workflow1

on:
  push:
    branches:
      - main
jobs:
  tareas:
    runs-on: ubuntu-latest

    steps:
    - name: 1.Descargar repositorio
      uses: actions/checkout@v4
      
    - name: 2. Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: 2. Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./app/Dockerfile
        push: true
        tags: nagoregomez/as-laboratorio-8-web
        
    - name: 3. Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_TOKEN }}
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        
    - name: 4. Authenticate with GKE
      uses: simenandre/setup-gke-gcloud-auth-plugin@v1

    - name: 5. Set up kubectl 
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: autopilot-cluster-1
        location: us-central1

    - name: 6. Deploy Kubernetes objects
      run: kubectl apply -f web-deployment.yaml 
        kubectl rollout restart deployment web-deployment.yaml 
        kubectl apply -f db-deployment.yaml
        kubectl rollout restart deployment db-deployment.yaml 

    - name: 6. Deploy web deployment
      run: kubectl apply -f web-deployment.yaml
    - name: 6. Restart web deployment
      run: kubectl rollout restart deployment web-deployment

    - name: 6. Deploy db deployment
      run: kubectl apply -f db-deployment.yaml
    - name: 6. Restart db deployment
      run: kubectl rollout restart deployment db-deployment
