name: workflow1

on:
  push:
    branches:
      - main
jobs:
  tareas:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4
      
    - name: Login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./app/Dockerfile
        push: true
        tags: nagoregomez/as-laboratorio-8-web
