name: testWorkflow

on:
  push:
    branches-ignore:
      - main
jobs:
  pasos:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write

    steps:
    - name: 1. Descargar repo
      uses: actions/checkout@v4

    - name: 2. Pruebas
      uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: pylint
